#!/bin/bash

firejail --noprofile "--private=$(dirname "$0")" \
         "--env=PATH=$HOME/.local/bin:$PATH" \
         "--env=LD_LIBRARY_PATH=$HOME/build/lib/x86_64-linux-gnu:$HOME/build/lib/i386-linux-gnu" \
         "--env=LD_PRELOAD=libsteam_api.so" \
         "--env=WINEDLLPATH=$HOME/build/lib/x86_64-linux-gnu:$HOME/build/lib/i386-linux-gnu" \
         "--env=WINEPREFIX=$HOME/.wine64" \
         "--env=WINEDLLOVERRIDES=steamclient.dll,steamclient64.dll,steam_api.dll,steam_api64.dll,csteamworks.dll=b" \
         bash
