1 cdecl SteamAPI_RestartAppIfNecessary() _SteamAPI_RestartAppIfNecessary
2 cdecl SteamAPI_Init() _SteamAPI_Init
3 cdecl SteamClient() _SteamClient
4 cdecl SteamUser() _SteamUser
5 cdecl SteamGameServer() _SteamGameServer
6 cdecl SteamFriends() _SteamFriends
7 cdecl SteamUtils() _SteamUtils
8 cdecl SteamMatchmaking() _SteamMatchmaking
9 cdecl SteamMatchmakingServers() _SteamMatchmakingServers
10 cdecl SteamUserStats() _SteamUserStats
11 cdecl SteamGameServerStats() _SteamGameServerStats
12 cdecl SteamApps() _SteamApps
13 cdecl SteamNetworking() _SteamNetworking
14 cdecl SteamRemoteStorage() _SteamRemoteStorage
15 cdecl SteamScreenshots() _SteamScreenshots
16 cdecl SteamHTTP() _SteamHTTP
17 cdecl SteamController() _SteamController
18 cdecl SteamUGC() _SteamUGC
19 cdecl SteamAppList() _SteamAppList
20 cdecl SteamMusic() _SteamMusic
21 cdecl SteamMusicRemote() _SteamMusicRemote
22 cdecl SteamHTMLSurface() _SteamHTMLSurface
23 cdecl SteamInventory() _SteamInventory
24 cdecl SteamVideo() _SteamVideo
25 cdecl SteamParentalSettings() _SteamParentalSettings
